# Generated by Django 5.0.3 on 2026-03-30 09:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0002_paymenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='BDE',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'BDEs',
                'ordering': ['name'],
            },
        ),
    ]
