# Generated by Django 5.0.3 on 2026-04-01 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0003_bde'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BDE',
        ),
    ]
