# Generated by Django 5.0.3 on 2026-03-17 11:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_type', models.CharField(choices=[('new_payment', 'New Payment'), ('remaining_payment', 'Remaining Payment'), ('complimentary', 'Complimentary'), ('converted', 'Converted'), ('transfer', 'Transfer')], max_length=30)),
                ('bank_account', models.CharField(blank=True, max_length=255, null=True)),
                ('booking_date', models.DateField()),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('bde_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bde_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booking_date', '-created_at'],
            },
        ),
    ]
