# Generated by Django 6.0.3 on 2026-03-20 12:05

import bookings.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('branch_name', models.CharField(blank=True, max_length=200)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('account_holder_name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['bank_name', 'account_number'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bde_name', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_type', models.CharField(choices=[('new_payment', 'New Payment'), ('remaining_payment', 'Remaining Payment'), ('complimentary', 'Complimentary'), ('converted', 'Converted'), ('transfer', 'Transfer')], max_length=30)),
                ('booking_date', models.DateField()),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('total_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_payment_remarks', models.TextField(blank=True, null=True)),
                ('received_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('received_amount_remarks', models.TextField(blank=True, null=True)),
                ('remaining_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remaining_amount_remarks', models.TextField(blank=True, null=True)),
                ('after_fund_disbursement_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('after_fund_disbursement_remarks', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=bookings.models.booking_attachment_upload_to)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.bank')),
            ],
            options={
                'ordering': ['-booking_date', '-created_at'],
            },
        ),
    ]
