# Generated by Django 5.0.3 on 2026-03-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='lead_source',
            field=models.CharField(blank=True, choices=[('google', 'Google'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('referral', 'Referral'), ('cold_call', 'Cold Call'), ('website', 'Website'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
