# Generated by Django 6.0.3 on 2026-03-21 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0001_initial'),
        ('bookings', '0003_booking_lead_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='lead_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='attributes.leadsource'),
        ),
    ]
