# Generated by Django 6.0.3 on 2026-03-21 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0002_paymenttype'),
        ('bookings', '0004_alter_booking_lead_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='attributes.paymenttype'),
        ),
    ]
