# Generated by Django 5.0.3 on 2026-03-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_booking_bank_account_bank_booking_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='bde_user',
        ),
        migrations.AddField(
            model_name='booking',
            name='bde_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
