# Generated by Django 5.0.3 on 2026-04-06 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='after_fund_disbursement_remarks',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='received_amount_remarks',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='remaining_amount_remarks',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_payment_remarks',
        ),
    ]
