# Generated by Django 5.0.3 on 2026-03-23 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
    ]
