# Generated by Django 6.0.3 on 2026-03-26 00:00

import django.db.models.deletion
import services.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_industry'),
        ('services', '0003_remove_service_category_delete_servicecategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='client_primary_contact',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='dependencies_blockers',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='documents_received',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='handoff_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='handoff_rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='handoff_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='handoff_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_service_handoffs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='handoff_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='handoff_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='payment_visibility_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='promised_timeline',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service_scope',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['handoff_status'], name='idx_service_req_handoff'),
        ),
        migrations.CreateModel(
            name='ClientDocumentPortal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('instructions', models.TextField(blank=True, default='')),
                ('token', models.CharField(default=services.models.generate_document_portal_token, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_shared_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_portal', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_portals', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_document_portals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['client__company_name', 'client__client_name'],
            },
        ),
        migrations.CreateModel(
            name='ClientDocumentRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_required', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='services.clientdocumentportal')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientDocumentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=services.models.client_document_upload_to)),
                ('note', models.TextField(blank=True, default='')),
                ('submitted_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('submitted_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_submissions', to='clients.client')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='services.clientdocumentportal')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='services.clientdocumentrequirement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='clientdocumentsubmission',
            index=models.Index(fields=['client'], name='idx_doc_submission_client'),
        ),
        migrations.AddIndex(
            model_name='clientdocumentsubmission',
            index=models.Index(fields=['portal'], name='idx_doc_submission_portal'),
        ),
    ]
