# Generated by Django 6.0.3 on 2026-03-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskcolumn',
            unique_together={('board', 'name', 'tenant')},
        ),
        migrations.AlterField(
            model_name='taskcolumn',
            name='status_key',
            field=models.CharField(max_length=50),
        ),
    ]
