# Generated by Django 6.0.3 on 2026-03-20 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email'], name='idx_client_email'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['company_name'], name='idx_client_company'),
        ),
    ]
