# Generated by Django 5.0.3 on 2026-03-28 08:01

import django.db.models.deletion
import payroll.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_address', models.TextField(blank=True)),
                ('company_logo', models.FileField(blank=True, null=True, upload_to=payroll.models.payroll_logo_upload_to)),
                ('payslip_title', models.CharField(default='Payslip', max_length=100)),
                ('default_working_days', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('leave_types', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_code', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('designation', models.CharField(blank=True, max_length=150)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('work_location', models.CharField(blank=True, max_length=150)),
                ('pan_number', models.CharField(blank=True, max_length=20)),
                ('uan_number', models.CharField(blank=True, max_length=30)),
                ('pf_number', models.CharField(blank=True, max_length=30)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('bank_ifsc', models.CharField(blank=True, max_length=20)),
                ('annual_ctc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['full_name', 'employee_code'],
                'indexes': [models.Index(fields=['employee_code'], name='idx_payroll_employee_code'), models.Index(fields=['full_name'], name='idx_payroll_employee_name')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction'), ('employer_contribution', 'Employer Contribution')], default='earning', max_length=32)),
                ('formula_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('remainder', 'Balance / Remainder')], default='percentage', max_length=32)),
                ('basis', models.CharField(choices=[('monthly_ctc', 'Monthly CTC'), ('gross_earnings', 'Gross Earnings'), ('component', 'Another Component')], default='monthly_ctc', max_length=32)),
                ('reference_component', models.CharField(blank=True, max_length=100)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('apply_proration', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_salary_components', to='payroll.payrollemployee')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.DateField(help_text='Store the first day of the month.')),
                ('total_days', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5)),
                ('paid_days', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5)),
                ('leave_without_pay_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('leave_breakdown', models.JSONField(blank=True, default=list)),
                ('annual_ctc_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('monthly_ctc_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('earnings_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('deductions_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('employer_contributions_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('loss_of_pay_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('company_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('company_address_snapshot', models.TextField(blank=True)),
                ('employee_snapshot', models.JSONField(blank=True, default=dict)),
                ('calculation_snapshot', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslips', to='payroll.payrollconfiguration')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payslips', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='payroll.payrollemployee')),
            ],
            options={
                'ordering': ['-month', 'employee__full_name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction'), ('employer_contribution', 'Employer Contribution')], default='earning', max_length=32)),
                ('formula_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('remainder', 'Balance / Remainder')], default='percentage', max_length=32)),
                ('basis', models.CharField(choices=[('monthly_ctc', 'Monthly CTC'), ('gross_earnings', 'Gross Earnings'), ('component', 'Another Component')], default='monthly_ctc', max_length=32)),
                ('reference_component', models.CharField(blank=True, max_length=100)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('apply_proration', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_components', to='payroll.payrollconfiguration')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='employeesalarycomponent',
            constraint=models.UniqueConstraint(fields=('employee', 'name'), name='uniq_payroll_employee_component_name_per_employee'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('employee', 'month'), name='uniq_payroll_payslip_per_employee_month'),
        ),
        migrations.AddConstraint(
            model_name='salarycomponent',
            constraint=models.UniqueConstraint(fields=('configuration', 'name'), name='uniq_payroll_component_name_per_configuration'),
        ),
    ]
