# Generated by Django 5.0.3 on 2026-03-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='bde_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
