# Generated by Django 6.0.3 on 2026-03-21 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0001_initial'),
        ('leads', '0002_lead_bde_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='attributes.leadsource'),
        ),
    ]
