# Generated by Django 5.0.3 on 2026-03-23 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_source'),
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Service the lead is interested in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='services.service'),
        ),
    ]
