# Generated by Django 5.0.3 on 2026-03-23 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0002_paymenttype'),
        ('clients', '0003_alter_client_industry'),
        ('leads', '0004_lead_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='attributes.industry'),
        ),
        migrations.AddField(
            model_name='lead',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Link to the master client record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='clients.client'),
        ),
    ]
