# Generated by Django 5.0.3 on 2026-03-24 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_payment_type'),
        ('leads', '0005_lead_client_name_lead_company_name_lead_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assigned_at',
            field=models.DateTimeField(blank=True, help_text='When the lead was assigned to the current owner', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='assignment_method',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('auto', 'Auto'), ('round_robin', 'Round Robin')], help_text='How this lead was assigned', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_at',
            field=models.DateTimeField(blank=True, help_text='When the lead was converted to a booking', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_booking',
            field=models.ForeignKey(blank=True, help_text='Booking created from this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lead', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='lead',
            name='first_response_at',
            field=models.DateTimeField(blank=True, help_text='When the lead was first contacted', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='interested_at',
            field=models.DateTimeField(blank=True, help_text='When the lead first showed interest', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent activity on this lead', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_status_reason',
            field=models.CharField(blank=True, help_text='Reason for current status, e.g. why lost or why qualified', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lost_reason',
            field=models.CharField(blank=True, help_text='Specific reason if lead was lost', max_length=255, null=True),
        ),
    ]
