# Generated by Django 5.0.3 on 2026-03-25 05:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0002_paymenttype'),
        ('leads', '0006_lead_assigned_at_lead_assignment_method_and_more'),
        ('services', '0003_remove_service_category_delete_servicecategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAssignmentRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('priority', models.IntegerField(default=0, help_text='Higher number = checked first')),
                ('strategy', models.CharField(choices=[('round_robin', 'Round Robin'), ('load_balanced', 'Load Balanced (Future)')], default='round_robin', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('eligible_users', models.ManyToManyField(help_text='Users who can receive leads under this rule', related_name='assignment_rules', to=settings.AUTH_USER_MODEL)),
                ('last_assigned_user', models.ForeignKey(blank=True, help_text='Tracked for Round Robin logic', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_rule_assignments', to=settings.AUTH_USER_MODEL)),
                ('trigger_service', models.ForeignKey(blank=True, help_text='If interested service matches this, the rule triggers', null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service')),
                ('trigger_source', models.ForeignKey(blank=True, help_text='If lead source matches this, the rule triggers', null=True, on_delete=django.db.models.deletion.CASCADE, to='attributes.leadsource')),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
    ]
