# Generated by Django 5.0.3 on 2026-04-01 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_leadassignmentrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The BDE or Admin who recorded this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lead',
            name='bde_name',
            field=models.CharField(blank=True, help_text='Deprecated: use created_by for system users', max_length=255, null=True),
        ),
    ]
