# Generated by Django 5.0.3 on 2026-03-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('sales_manager', 'Sales Manager'), ('booking_ops', 'Booking Ops'), ('finance', 'Finance'), ('hr', 'HR'), ('service_ops', 'Service Ops')], help_text='System role for access control. BDEs use public forms and do not have system roles.', max_length=30, null=True),
        ),
    ]
