# Generated by Django 5.0.3 on 2026-04-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('sales_manager', 'Business Development Manager'), ('booking_ops', 'Booking Ops'), ('finance', 'Finance'), ('hr', 'HR'), ('service_ops', 'Service Ops'), ('bde', 'Business Development Executive')], help_text='System role for access control.', max_length=30, null=True),
        ),
    ]
